# Generated by Django 6.0.7 on 2026-07-16 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=50, null=True)),
                ('date_achat', models.DateField(auto_now_add=True)),
                ('avec_tva', models.BooleanField(default=False)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_charge', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('type_remise', models.CharField(choices=[('AUCUNE', 'Aucune'), ('POURCENTAGE', 'Pourcentage (%)'), ('MONTANT', 'Montant Fixe (DH)')], default='AUCUNE', max_length=15)),
                ('valeur_remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avec_tva', models.BooleanField(default=False)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ParametresSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva_vente_mode', models.CharField(choices=[('OUI', 'Toujours'), ('NON', 'Jamais'), ('MIXTE', 'Au Choix')], default='MIXTE', max_length=10)),
                ('tva_achat_mode', models.CharField(choices=[('OUI', 'Toujours'), ('NON', 'Jamais'), ('MIXTE', 'Au Choix')], default='MIXTE', max_length=10)),
                ('taux_tva_defaut', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ice', models.CharField(blank=True, max_length=50, null=True)),
                ('type_tier', models.CharField(choices=[('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur')], default='CLIENT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='compta.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='compta.achat')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode', models.CharField(choices=[('ESPECE', 'Espèce'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement')], default='ESPECE', max_length=20)),
                ('remarque', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.tier')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(limit_choices_to={'type_tier': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, to='compta.tier'),
        ),
        migrations.AddField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(limit_choices_to={'type_tier': 'FOURNISSEUR'}, on_delete=django.db.models.deletion.CASCADE, to='compta.tier'),
        ),
    ]
